Algoritmo "EXERCICIO 35"

algoritmo "DiaDaSemanaComCaso"
var
   dia: inteiro

inicio

   escreva("Digite um número de 1 a 7: ")
   leia(dia)

   caso dia de
      1: escreva("Domingo")
      2: escreva("Segunda-feira")
      3: escreva("Terça-feira")
      4: escreva("Quarta-feira")
      5: escreva("Quinta-feira")
      6: escreva("Sexta-feira")
      7: escreva("Sábado")
   outro
      escreva("Erro: Número inválido! Digite um número de 1 a 7.")
   fimcaso

fimalgoritmo